a_0 = int(input('Enter a integer number for arithmetic operation:'))
b_0 = int(input('Enter a another integer number for arithmetic operation:'))
print(a_0 + b_0, 'in Addition')
print(a_0 - b_0, 'in Subtraction')
print(a_0 * b_0, 'in Multiplication')
print(a_0 // b_0, 'in Floor division')
print(a_0 % b_0, 'in Modulus')
